# This is a syntactically invalid query file but it serves to demonstrate all
# the SPARQL syntax features

BASE <http://base>
PREFIX ex: <http://example.org>

SELECT (true AS ?true) (<http://some/uri> AS ?example) ("test" AS ?literal)
FROM NAMED <http://graph>
WHERE
{
  # Check highlighting of different syntax elements
  # BUG URIs are highlighted incorrectly, should include the < > brackets
  VALUES ?x { <http://example.org/path/to/file.ext?querystring#fragment> }
  BIND(ISURI(?x) AS ?uri)
  MINUS { ?y a ?type }
  GRAPH ?g { }
  { {} UNION {} }
  OPTIONAL { }
  SERVICE <http://endpoint> { }

  # Check highlighting of some functions
  FILTER EXISTS { ?x a ?type }
  FILTER NOT EXISTS { ?x a ?type }
  FILTER CONTAINS(STR(?x), "foo")
  FILTER CONTAINS( STR(?x), "bar")
  FILTER ?x IN ("foo", "bar")
  FILTER ?x NOT IN ("faz")

  # Check highlighting of operators
  FILTER(1 && 2 || !false || 4 > 5 || 4 < 5 || 4 + 5 || 4 - 5 || 4 * 5 || 4 / 5 || 4 != 5 || 4 = 5 || 4 >= 5 || 4 <= 5)
  BIND("contains" AS ?containsString)
}
GROUP BY ?x
HAVING (COUNT(?x) > 2)
LIMIT 5 OFFSET 10
ORDER BY ASC(?foo) DESC(?bar)
