# This is a syntactically invalid query file but it serves to demonstrate all
# the SPARQL syntax features

BASE <http://base>
PREFIX ex: <http://example.org>

SELECT (true AS ?true) (<http://some/uri> AS ?example) ("test" AS ?literal)
FROM NAMED <http://graph>
WHERE
{
  # Check highlighting of different syntax elements
  VALUES ?x { <http://example.org/path/to/file.ext?querystring#fragment> "text" "text"^^<http://datatype> "text"@en [] _:blank 123 12.3 1.2e3 true false UNDEF}
  BIND(ISURI(?x) AS ?uri)
  MINUS { ?y a ?type }
  GRAPH ?g { }
  { {} UNION {} }
  OPTIONAL { }
  SERVICE <http://endpoint> { }

  # Deep nesting and folding
  # Graph Pattern braces are marked as fold points
  {
    {
      {
        # 5 levels deep
        {
          # 6 levels deep - beyond this point vim should fold by default since we define the foldlevel to be 5
          # Use :foldopen to open the fold
          {
            # 7 levels deep
            {
              # 8 levels deep
              {
                 # 9 levels deep
              }
            }
          }
        }
      }
    }
  }
  # Blank Node braces are also marked as fold points
  [ ?a [ ?b [ ?c [ ?d [ ?e ] ] ] ] ]
  # As well as function call braces
  BIND(STR(STR(STR(STR(STR(STR(STR(STR(?a)))))))))

  # Check highlighting of some functions
  FILTER EXISTS { ?x a ?type }
  FILTER NOT EXISTS { ?x a ?type }
  FILTER CONTAINS(STR(?x), "foo")
  FILTER ?x IN ("foo", "bar")
  FILTER ?x NOT IN ("faz")

  # Check highlighting of operators
  FILTER(1 && 2 || !false || 4 > 5 || 4 < 5 || 4 + 5 || 4 - 5 || 4 * 5 || 4 / 5 || 4 != 5 || 4 = 5 || 4 >= 5 || 4 <= 5)
  BIND("contains" AS ?containsString)
}
GROUP BY ?x
HAVING (COUNT(?x) > 2)
LIMIT 5 OFFSET 10
ORDER BY ASC(?foo) DESC(?bar)
